### ISSUE TITLE
[JOSS review] Contribution and authorship

### ISSUE THREAD

**Issue by MoLi7** [Mat-dp/mat-dp-core#20]
Hi @kcerva 

I'm reviewing your submission in https://github.com/openjournals/joss-reviews/issues/4460. It seems that the authors of your submission didn't make major contribution to the software directly in your repo, while the major contributors to the software are not listed as co-authors in your paper. This makes me unable to check this one below.

- [ ] Contribution and authorship: Has the submitting author (@kcerva) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

Could you provide justification to this? Thanks!

**Comment by kcerva** [comment]
Hi @MoLi7. Thanks for this observation. In this particular repository, my contributions seem small because this repository refers to refactoring of the original Mat-dp model- which was originally in another one of my repositories. This is why the copyright notice gives information about copyright citing the original repository and then talks about modifications. The other contributors to this modified version of the model helped to flesh out attributes of the code that are more in line with proper software development practices and were working under instruction and supervision from myself and Jonathan Cullen. These contributors were externally hired and agreed to cede IP and copyright to the university- a common practice for externally hired software developers. I hope this clarifies things.

**Comment by MoLi7** [comment]
Thank you for the clarification @kcerva
